# Logistic Regression with NaN Handling

In [216]:
import pandas as pd
import numpy as np

In [217]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model.logistic import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [218]:
df_real = pd.read_csv('../data/data_real.csv')
df_fake = pd.read_csv('../data/data_fake.csv')

In [219]:
df_real.head()

,profile_pic,biography,follows_count,followed_by_count,ff_ratio,media_count,is_private,is_verified,is_business_account,is_joined_recently,...,std_comments,var_comments,skw_comments,mean_time_between_posts,max_time_between_posts,min_time_between_posts,std_time_between_posts,var_time_between_posts,skw_time_between_posts,real_account
0,True,False,1128,575,0.509300,322,False,False,False,False,...,1.527525,2.333333,1.131088,1.491866e+06,7517421.0,5.0,1.832700e+06,3.358789e+12,1.797422,True
1,True,True,430,353,0.819026,3,False,False,True,False,...,9.237604,85.333333,0.707107,5.472764e+06,6023604.0,4921924.0,7.790054e+05,6.068494e+11,0.000000,True
2,True,True,418,534,1.274463,139,False,False,False,False,...,7.131620,50.860000,0.321661,3.611337e+06,10774210.0,164203.0,3.163705e+06,1.000903e+13,1.065019,True
3,True,True,1425,3118,2.186536,206,False,False,True,False,...,11.146449,124.243333,0.682247,1.338888e+06,4057835.0,233556.0,1.025556e+06,1.051766e+12,0.939111,True
4,True,True,953,288,0.301887,458,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True

In [220]:
df_real.describe()

,follows_count,followed_by_count,ff_ratio,media_count,highlight_reel_count,average_likes,max_likes,min_likes,std_likes,var_likes,...,min_comments,std_comments,var_comments,skw_comments,mean_time_between_posts,max_time_between_posts,min_time_between_posts,std_time_between_posts,var_time_between_posts,skw_time_between_posts
count,9645.000000,9.645000e+03,9.645000e+03,9645.000000,9645.000000,5.457000e+03,5.457000e+03,5.457000e+03,5.433000e+03,5.433000e+03,...,5457.000000,5433.000000,5.433000e+03,5457.000000,5.433000e+03,5.433000e+03,5.433000e+03,5.414000e+03,5.414000e+03,5433.000000
mean,946.835874,6.039297e+05,2.907253e+04,693.215967,5.833178,2.393746e+04,5.727100e+04,7.047186e+03,1.260258e+04,9.895814e+09,...,35.102804,225.148842,7.611672e+06,1.640635,1.334810e+06,6.572650e+06,1.278859e+05,1.729140e+06,1.514431e+13,1.656720
std,1178.552407,6.173197e+06,1.420129e+06,1567.932075,19.149049,1.956982e+05,4.512957e+05,6.342862e+04,9.868526e+04,1.884072e+11,...,338.678749,2749.976630,2.940647e+08,1.009689,2.937520e+06,1.236299e+07,1.929702e+06,3.486636e+06,1.082681e+14,0.987025
min,0.000000,2.000000e+00,4.651811e-02,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,4.358899e-01,1.900000e-01,...,0.000000,0.000000,0.000000e+00,-3.328201,4.000000e+00,5.000000e+00,0.000000e+00,1.414214e+00,2.000000e+00,-3.293188
25%,328.000000,5.020000e+02,8.515815e-01,69.000000,0.000000,5.116667e+01,9.900000e+01,2.000000e+01,1.898359e+01,3.603767e+02,...,0.000000,1.903506,3.623333e+00,0.927672,2.081567e+05,6.886220e+05,2.288000e+03,1.697976e+05,2.883123e+10,0.975564
50%,617.000000,1.135000e+03,1.554113e+00,230.000000,1.000000,1.304400e+02,2.590000e+02,5.300000e+01,4.919173e+01,2.419827e+03,...,0.000000,4.048868,1.639333e+01,1.474520,5.696260e+05,2.436319e+06,2.994100e+04,6.172486e+05,3.809960e+11,1.539357
75%,1037.000000,1.229500e+04,1.698335e+01,650.000000,7.000000,1.049200e+03,2.475000e+03,3.180000e+02,5.248149e+02,2.754307e+05,...,2.000000,17.905958,3.206233e+02,2.182501,1.529636e+06,7.420666e+06,8.340300e+04,1.873575e+06,3.510286e+12,2.223599
max,7832.000000,3.239658e+08,1.374144e+08,33287.000000,1143.000000,6.210486e+06,1.546886e+07,2.616220e+06,3.013303e+06,9.079997e+12,...,15388.000000,130429.914201,1.701196e+10,4.694855,1.369621e+08,1.510523e+08,1.369621e+08,6.327939e+07,4.004282e+15,4.587317

In [221]:
df_real.fillna(df_real.median(),inplace=True)

In [222]:
df_fake.fillna(df_fake.median(),inplace=True)
df_fake.head()

,profile_pic,biography,follows_count,followed_by_count,ff_ratio,media_count,is_private,is_verified,is_business_account,is_joined_recently,...,std_comments,var_comments,skw_comments,mean_time_between_posts,max_time_between_posts,min_time_between_posts,std_time_between_posts,var_time_between_posts,skw_time_between_posts,real_account
0,True,True,2321,747,0.321705,10,True,False,False,False,...,0.758287,0.575,1.278019,483928.833333,1880233.5,114.5,582273.486384,3.390424e+11,1.606342,False
1,True,True,4247,611,0.143832,99,False,False,True,False,...,0.758287,0.575,1.278019,483928.833333,1880233.5,114.5,582273.486384,3.390424e+11,1.606342,False
2,True,True,781,338,0.432225,128,True,False,False,False,...,0.758287,0.575,1.278019,483928.833333,1880233.5,114.5,582273.486384,3.390424e+11,1.606342,False
3,True,True,1764,1613,0.913881,64,False,False,False,False,...,0.758287,0.575,1.278019,483928.833333,1880233.5,114.5,582273.486384,3.390424e+11,1.606342,False
4,True,False,68,65,0.942029,1,False,False,False,False,...,0.758287,0.575,1.278019,483928.833333,1880233.5,114.5,582273.486384,3.390424e+11,1.606342,False

In [223]:
df=pd.concat([df_real,df_fake],ignore_index=True)

In [224]:
print(df)

       profile_pic  biography  follows_count  followed_by_count  ff_ratio  \
0             True      False           1128                575  0.509300
1             True       True            430                353  0.819026
2             True       True            418                534  1.274463
3             True       True           1425               3118  2.186536
4             True       True            953                288  0.301887
...            ...        ...            ...                ...       ...
17482         True       True           2323                 72  0.030981
17483         True       True           2311               2934  1.269031
17484         True       True           7498               2340  0.312042
17485         True      False           6321                327  0.051724
17486         True       True           6531                 61  0.009339

       media_count  is_private  is_verified  is_business_account  \
0              322       False        False                False
1                3       False        False                 True
2              139       False        False                False
3              206       False        False                 True
4              458        True        False                False
...            ...         ...          ...                  ...
17482           20       False        False                False
17483           55       False        False                False
17484           39       False        False                 True
17485           15       False        False                False
17486            7       False        False                False

       is_joined_recently  ...  std_comments  var_comments  skw_comments  \
0                   False  ...      1.527525      2.333333      1.131088
1                   False  ...      9.237604     85.333333      0.707107
2                   False  ...      7.131620     50.860000      0.321661
3                   False  ...     11.146449    124.243333      0.682247
4                   False  ...      4.048868     16.393333      1.474520
...                   ...  ...           ...           ...           ...
17482               False  ...      6.340347     40.200000      1.582760
17483               False  ...      0.472582      0.223333      2.951336
17484               False  ...      3.329164     11.083333      0.677680
17485               False  ...      2.313521      5.352381      2.028695
17486               False  ...      0.000000      0.000000      0.000000

       mean_time_between_posts  max_time_between_posts  \
0                 1.491866e+06               7517421.0
1                 5.472764e+06               6023604.0
2                 3.611337e+06              10774210.0
3                 1.338888e+06               4057835.0
4                 5.696260e+05               2436319.0
...                        ...                     ...
17482             2.975948e+05               2685349.0
17483             6.898008e+05               6434047.0
17484             9.702668e+05               3269496.0
17485             3.078766e+06              16860832.0
17486             8.326883e+05               1910995.0

       min_time_between_posts  std_time_between_posts  var_time_between_posts  \
0                         5.0            1.832700e+06            3.358789e+12
1                   4921924.0            7.790054e+05            6.068494e+11
2                    164203.0            3.163705e+06            1.000903e+13
3                    233556.0            1.025556e+06            1.051766e+12
4                     29941.0            6.172486e+05            3.809960e+11
...                       ...                     ...                     ...
17482                    23.0            7.634178e+05            5.828067e+11
17483                   138.0            1.780056e+06            3.168601e+12
17484                   280.0            7.913546e+05            6.262421e+11
17485                    10.0            5.588747e+06            3.123409e+13
17486                522383.0            5.305299e+05            2.814620e+11

       skw_time_between_posts  real_account
0                    1.797422          True
1                    0.000000          True
2                    1.065019          True
3                    0.939111          True
4                    1.539357          True
...                       ...           ...
17482                2.578928         False
17483                2.400901         False
17484                1.132687         False
17485                1.579750         False
17486                1.753490         False

[17487 rows x 31 columns]

In [225]:
# df.drop('Unnamed: 0', axis=1, inplace=True)

In [226]:
features_columns=list(df.columns[:30])
# targets_column=list(df.columns[30:31])
# df.head()
print(features_columns)

['profile_pic', 'biography', 'follows_count', 'followed_by_count', 'ff_ratio', 'media_count', 'is_private', 'is_verified', 'is_business_account', 'is_joined_recently', 'highlight_reel_count', 'connected_fb_page', 'average_likes', 'max_likes', 'min_likes', 'std_likes', 'var_likes', 'skw_likes', 'average_comments', 'max_comments', 'min_comments', 'std_comments', 'var_comments', 'skw_comments', 'mean_time_between_posts', 'max_time_between_posts', 'min_time_between_posts', 'std_time_between_posts', 'var_time_between_posts', 'skw_time_between_posts']

In [227]:
df.shape

(17487, 31)

In [228]:
# cl_f = {'pos': 1, 'neg': 0}
# df['Class'] = df['Class'].map(cl_f)

In [234]:
df.dropna(inplace=True)
df.shape

(17487, 31)

In [188]:
targets = df['real_account'].values

In [189]:
targets

array([ True,  True,  True, ..., False, False, False])

In [190]:
# df.drop('real_account', axis=1, inplace=True)

In [191]:
df.head()

,profile_pic,biography,follows_count,followed_by_count,ff_ratio,media_count,is_private,is_verified,is_business_account,is_joined_recently,...,std_comments,var_comments,skw_comments,mean_time_between_posts,max_time_between_posts,min_time_between_posts,std_time_between_posts,var_time_between_posts,skw_time_between_posts,real_account
0,True,False,1128,575,0.509300,322,False,False,False,False,...,1.527525,2.333333,1.131088,1.491866e+06,7517421.0,5.0,1.832700e+06,3.358789e+12,1.797422,True
1,True,True,430,353,0.819026,3,False,False,True,False,...,9.237604,85.333333,0.707107,5.472764e+06,6023604.0,4921924.0,7.790054e+05,6.068494e+11,0.000000,True
2,True,True,418,534,1.274463,139,False,False,False,False,...,7.131620,50.860000,0.321661,3.611337e+06,10774210.0,164203.0,3.163705e+06,1.000903e+13,1.065019,True
3,True,True,1425,3118,2.186536,206,False,False,True,False,...,11.146449,124.243333,0.682247,1.338888e+06,4057835.0,233556.0,1.025556e+06,1.051766e+12,0.939111,True
4,True,True,953,288,0.301887,458,True,False,False,False,...,4.048868,16.393333,1.474520,5.696260e+05,2436319.0,29941.0,6.172486e+05,3.809960e+11,1.539357,True

In [232]:
df.shape

(17487, 31)

In [193]:
print(df)

       profile_pic  biography  follows_count  followed_by_count  ff_ratio  \
0             True      False           1128                575  0.509300
1             True       True            430                353  0.819026
2             True       True            418                534  1.274463
3             True       True           1425               3118  2.186536
4             True       True            953                288  0.301887
...            ...        ...            ...                ...       ...
17482         True       True           2323                 72  0.030981
17483         True       True           2311               2934  1.269031
17484         True       True           7498               2340  0.312042
17485         True      False           6321                327  0.051724
17486         True       True           6531                 61  0.009339

       media_count  is_private  is_verified  is_business_account  \
0              322       False        False                False
1                3       False        False                 True
2              139       False        False                False
3              206       False        False                 True
4              458        True        False                False
...            ...         ...          ...                  ...
17482           20       False        False                False
17483           55       False        False                False
17484           39       False        False                 True
17485           15       False        False                False
17486            7       False        False                False

       is_joined_recently  ...  std_comments  var_comments  skw_comments  \
0                   False  ...      1.527525      2.333333      1.131088
1                   False  ...      9.237604     85.333333      0.707107
2                   False  ...      7.131620     50.860000      0.321661
3                   False  ...     11.146449    124.243333      0.682247
4                   False  ...      4.048868     16.393333      1.474520
...                   ...  ...           ...           ...           ...
17482               False  ...      6.340347     40.200000      1.582760
17483               False  ...      0.472582      0.223333      2.951336
17484               False  ...      3.329164     11.083333      0.677680
17485               False  ...      2.313521      5.352381      2.028695
17486               False  ...      0.000000      0.000000      0.000000

       mean_time_between_posts  max_time_between_posts  \
0                 1.491866e+06               7517421.0
1                 5.472764e+06               6023604.0
2                 3.611337e+06              10774210.0
3                 1.338888e+06               4057835.0
4                 5.696260e+05               2436319.0
...                        ...                     ...
17482             2.975948e+05               2685349.0
17483             6.898008e+05               6434047.0
17484             9.702668e+05               3269496.0
17485             3.078766e+06              16860832.0
17486             8.326883e+05               1910995.0

       min_time_between_posts  std_time_between_posts  var_time_between_posts  \
0                         5.0            1.832700e+06            3.358789e+12
1                   4921924.0            7.790054e+05            6.068494e+11
2                    164203.0            3.163705e+06            1.000903e+13
3                    233556.0            1.025556e+06            1.051766e+12
4                     29941.0            6.172486e+05            3.809960e+11
...                       ...                     ...                     ...
17482                    23.0            7.634178e+05            5.828067e+11
17483                   138.0            1.780056e+06            3.168601e+12
17484                   280.0            7.913546e+05            6.262421e+11
17485                    10.0            5.588747e+06            3.123409e+13
17486                522383.0            5.305299e+05            2.814620e+11

       skw_time_between_posts  real_account
0                    1.797422          True
1                    0.000000          True
2                    1.065019          True
3                    0.939111          True
4                    1.539357          True
...                       ...           ...
17482                2.578928         False
17483                2.400901         False
17484                1.132687         False
17485                1.579750         False
17486                1.753490         False

[17487 rows x 31 columns]

In [194]:
df_sc = StandardScaler().fit_transform(df)

In [243]:
x_train, x_test, y_train, y_test = train_test_split(df_sc, targets, test_size = 0.99, random_state = 12345)

In [244]:
lr = LogisticRegression()

In [245]:
lr.fit(x_train, y_train)

/Users/fernandodenitto/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [246]:
lr_pred = lr.predict(x_test)

In [247]:
lr.predict(x_test[14].reshape(1,-1))

array([ True])

In [248]:
from sklearn.metrics import confusion_matrix, classification_report

In [249]:
print(confusion_matrix(y_test, lr_pred))

[[7761    1]
 [   3 9548]]

In [250]:
print(classification_report(y_test, lr_pred))

              precision    recall  f1-score   support

       False       1.00      1.00      1.00      7762
        True       1.00      1.00      1.00      9551

    accuracy                           1.00     17313
   macro avg       1.00      1.00      1.00     17313
weighted avg       1.00      1.00      1.00     17313