# Dataset Analysis

The aim of this Jupyter Notebook is to navigate the Dataset used on the project for the users classification in Instagram. It is a labelled dataset where the label is the column 'real_account' with the possible values true (for the real users) and false (for the fake ones).

# Import the context (libraries) and the dataset (already processed)

In [51]:
import pandas as pd
import numpy as np

In [52]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler

In [53]:
df_real = pd.read_csv('../data/balanced_real_data.csv')
df_fake = pd.read_csv('../data/balanced_fake_data.csv')

# Fast view of Real and Fake Users Datasets

In [54]:
df_real.head()

,profile_pic,biography,follows_count,followed_by_count,ff_ratio,media_count,is_private,is_verified,is_business_account,is_joined_recently,...,std_comments,var_comments,skw_comments,mean_time_between_posts,max_time_between_posts,min_time_between_posts,std_time_between_posts,var_time_between_posts,skw_time_between_posts,real_account
0,True,45,2979,846,0.283988,278,False,False,False,False,...,4.964205,2.464333e+01,1.759163,1.688451e+06,7930005.0,75731.0,1.964306e+06,3.858496e+12,1.947676,True
1,True,131,966,5172,5.354037,150,False,False,True,False,...,0.472582,2.233333e-01,2.951336,1.978352e+05,851011.0,3855.0,2.222041e+05,4.937467e+10,1.785389,True
2,True,128,1662,1475,0.887485,403,False,False,True,False,...,5.961543,3.554000e+01,1.546427,2.950338e+05,1128895.0,9212.0,2.417832e+05,5.845911e+10,1.726161,True
3,True,0,236,111,0.470339,43,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
4,True,16,386,967516,2506.518135,34,False,True,True,False,...,1180.090381,1.392613e+06,0.319856,2.418942e+06,12726352.0,36.0,2.814164e+06,7.919517e+12,2.273966,True

In [55]:
df_fake.head()

,profile_pic,biography,follows_count,followed_by_count,ff_ratio,media_count,is_private,is_verified,is_business_account,is_joined_recently,...,std_comments,var_comments,skw_comments,mean_time_between_posts,max_time_between_posts,min_time_between_posts,std_time_between_posts,var_time_between_posts,skw_time_between_posts,real_account
0,True,56,2321,747,0.321844,10,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1,True,147,4247,611,0.143866,99,False,False,True,False,...,0.678233,0.460000,2.068805,80254.208333,1466742.0,10.0,2.973342e+05,8.840762e+10,4.488934,False
2,True,127,1764,1613,0.914399,64,False,False,False,False,...,10.224643,104.543333,3.196293,333885.000000,836121.0,27637.0,2.240602e+05,5.020299e+10,0.519589,False
3,True,0,68,65,0.955882,1,False,False,False,False,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,False
4,True,80,242,134,0.553719,80,False,False,False,False,...,0.624500,0.390000,4.086591,694503.000000,6477346.0,8.0,1.489132e+06,2.217513e+12,2.800966,False

# Analysis of number of Private Users in each Dataset (Real and Fake)

Below of every table it is possible to see the number of entries

In [56]:
df_real[df_real['is_private']==True]

,profile_pic,biography,follows_count,followed_by_count,ff_ratio,media_count,is_private,is_verified,is_business_account,is_joined_recently,...,std_comments,var_comments,skw_comments,mean_time_between_posts,max_time_between_posts,min_time_between_posts,std_time_between_posts,var_time_between_posts,skw_time_between_posts,real_account
3,True,0,236,111,0.470339,43,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
20,True,70,426,397,0.931925,164,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
25,True,0,530,708,1.335849,487,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
31,True,0,485,222,0.457732,79,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
35,True,133,1162,1166,1.003442,297,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7629,True,29,759,667,0.878788,175,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
7646,True,0,315,355,1.126984,15,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
7649,True,55,377,145,0.384615,572,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
7650,True,85,381,1881,4.937008,247,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
7653,True,0,1197,433,0.361738,104,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True

In [57]:
df_fake[df_fake['is_private']==True]

,profile_pic,biography,follows_count,followed_by_count,ff_ratio,media_count,is_private,is_verified,is_business_account,is_joined_recently,...,std_comments,var_comments,skw_comments,mean_time_between_posts,max_time_between_posts,min_time_between_posts,std_time_between_posts,var_time_between_posts,skw_time_between_posts,real_account
0,True,56,2321,747,0.321844,10,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
14,True,33,19,26,1.368421,6,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
19,False,51,2782,706,0.253774,7,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
25,True,0,2618,323,0.123377,0,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
37,True,0,1201,405,0.337219,16,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7622,True,33,547,322,0.588665,8,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
7627,True,0,155,139,0.896774,5,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
7638,True,14,7077,899,0.127031,13,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
7648,True,62,912,945,1.036184,513,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
7649,True,31,1440,504,0.350000,12,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

# Creation of the Final Dataset merging the ones above

In [58]:
# Merging the dataset with real and fake users
df=pd.concat([df_real,df_fake],ignore_index=True)

# Fix the inconsistensy in the Dataset

In the project we had use two different scrapers for avoid the problem of the limited numbers of request from Instagram. The first scraper catch the users informations and the second one collect the media and compute the statistics. It is possible that sometimes between the two different times we used the two scraper some user switch from private to public and viceversa. It's not possibile to get information from private users (it's a consistency problem) so the solution adopted is to switch the attribute private to public since when we collected the datas the users were public. Another possibility is to have an old public profile become private: also in this case the solution adopted is to switch the attribute public to private.

In [59]:
def fix_private_entries(dataset):
    dataset.loc[(dataset['is_private']==True)&(dataset['min_likes'].notnull()),['is_private']] = False
    dataset.loc[(dataset['is_private'] ==False)&(dataset['min_likes'].isnull())&(dataset['media_count']!=0),['is_private']]=True
    return dataset

In [60]:
df.loc[df['is_private'] ==True]

,profile_pic,biography,follows_count,followed_by_count,ff_ratio,media_count,is_private,is_verified,is_business_account,is_joined_recently,...,std_comments,var_comments,skw_comments,mean_time_between_posts,max_time_between_posts,min_time_between_posts,std_time_between_posts,var_time_between_posts,skw_time_between_posts,real_account
3,True,0,236,111,0.470339,43,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
20,True,70,426,397,0.931925,164,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
25,True,0,530,708,1.335849,487,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
31,True,0,485,222,0.457732,79,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
35,True,133,1162,1166,1.003442,297,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15276,True,33,547,322,0.588665,8,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
15281,True,0,155,139,0.896774,5,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
15292,True,14,7077,899,0.127031,13,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
15302,True,62,912,945,1.036184,513,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
15303,True,31,1440,504,0.350000,12,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

In [61]:
df.loc[(df['is_private'] ==True)&(df['min_likes'].notnull())]

,profile_pic,biography,follows_count,followed_by_count,ff_ratio,media_count,is_private,is_verified,is_business_account,is_joined_recently,...,std_comments,var_comments,skw_comments,mean_time_between_posts,max_time_between_posts,min_time_between_posts,std_time_between_posts,var_time_between_posts,skw_time_between_posts,real_account
64,True,61,1113,628,0.564241,555,True,False,False,False,...,1.339154,1.793333,0.430254,3.383401e+05,1035596.0,33293.0,2.100937e+05,4.413938e+10,1.591702,True
463,True,114,198,79655,402.297980,1524,True,False,False,False,...,20.938561,438.423333,2.255061,5.843446e+04,162763.0,697.0,5.368829e+04,2.882433e+09,0.656763,True
563,True,60,353,1683,4.767705,492,True,False,False,False,...,19.979323,399.173333,1.573629,1.465247e+06,13550111.0,85677.0,2.668473e+06,7.120749e+12,4.110943,True
632,True,89,2082,6546,3.144092,249,True,False,False,False,...,14.857994,220.760000,1.516364,5.305289e+05,1841059.0,1626.0,6.735562e+05,4.536780e+11,0.946825,True
1892,True,100,953,626,0.656873,101,True,False,False,False,...,1.997498,3.990000,1.026663,2.802345e+05,1185088.0,112.0,2.944434e+05,8.669695e+10,1.386961,True
2017,True,147,902,2602,2.884701,642,True,False,False,False,...,2.314447,5.356667,-0.031184,2.388503e+05,603786.0,33387.0,1.848744e+05,3.417853e+10,0.929054,True
2018,True,64,2039,338,0.165768,127,True,False,False,False,...,0.472582,0.223333,2.951336,3.520043e+05,5810554.0,44.0,1.259476e+06,1.586280e+12,3.780921,True
2430,True,141,211,189,0.895735,235,True,False,False,False,...,2.598076,6.750000,3.267823,9.213404e+05,3271641.0,429.0,9.779130e+05,9.563138e+11,0.931225,True
2589,True,4,375,588,1.568000,126,True,False,False,False,...,3.752777,14.083333,0.699061,3.648195e+06,13257047.0,75913.0,3.729993e+06,1.391285e+13,1.362470,True
3169,True,27,815,553,0.678528,228,True,False,False,False,...,2.527845,6.390000,1.652588,3.830910e+06,13276510.0,40864.0,3.664062e+06,1.342535e+13,1.185874,True
3170,True,147,1567,1014,0.647096,124,True,False,False,False,...,8.883130,78.910000,3.607127,3.764922e+05,1985024.0,451.0,4.977953e+05,2.478002e+11,2.145646,True
3225,True,126,1540,961,0.624026,1538,True,False,False,False,...,1.732051,3.000000,3.682848,1.804403e+05,778672.0,2469.0,1.599727e+05,2.559127e+10,2.244401,True
3295,True,45,801,240,0.299625,71,True,False,False,False,...,3.643259,13.273333,2.196468,1.339008e+06,13756552.0,35.0,3.547493e+06,1.258471e+13,2.914594,True
3320,True,0,530,494,0.932075,109,True,False,False,False,...,1.691153,2.860000,3.198243,1.029883e+06,4314974.0,864.0,1.241301e+06,1.540829e+12,1.462782,True
3503,True,42,325,1735,5.338462,668,True,False,False,False,...,6.642540,44.123333,2.708343,7.677355e+05,4044462.0,24186.0,9.923480e+05,9.847545e+11,1.871017,True
3507,True,47,1011,1164,1.151335,22,True,False,False,False,...,6.695123,44.824675,1.868299,2.073262e+06,6649680.0,174630.0,1.611430e+06,2.596705e+12,1.377332,True
3854,True,42,126,3018,23.952381,420,True,False,False,False,...,5.536846,30.656667,0.739772,4.776041e+05,2065987.0,8759.0,5.357750e+05,2.870548e+11,1.736398,True
3882,True,41,936,502,0.536325,273,True,False,False,False,...,1.707825,2.916667,0.891299,4.818757e+05,2365291.0,66095.0,5.978067e+05,3.573728e+11,2.291749,True
4046,True,0,333,354,1.063063,33,True,False,False,False,...,1.877942,3.526667,2.019335,2.108632e+06,6769025.0,89901.0,1.850111e+06,3.422910e+12,1.403884,True
4371,True,80,2864,5055,1.765014,85,True,False,False,False,...,1.598958,2.556667,2.105953,1.515798e+06,9251686.0,23.0,2.618323e+06,6.855614e+12,1.845048,True
4897,True,2,669,888,1.327354,639,True,False,False,False,...,2.573584,6.623333,1.002724,4.384995e+05,4035110.0,476.0,9.117011e+05,8.311990e+11,3.035207,True
5026,True,0,751,931,1.239680,537,True,False,False,False,...,2.208318,4.876667,0.869286,1.644710e+06,11925088.0,114810.0,2.558489e+06,6.545864e+12,2.993339,True
5098,True,0,354,890,2.514124,24,True,False,False,False,...,1.190999,1.418478,1.017891,2.874744e+06,18726342.0,96289.0,4.172031e+06,1.740584e+13,2.665449,True
5103,True,81,694,933,1.344380,304,True,False,False,False,...,1.423610,2.026667,1.364184,4.181502e+05,1853746.0,25800.0,3.937302e+05,1.550235e+11,2.302790,True
5147,True,129,1071,1765,1.647993,223,True,False,False,False,...,3.539303,12.526667,1.470685,3.591814e+06,17457018.0,270020.0,4.255636e+06,1.811044e+13,1.938437,True
5580,True,82,0,468953,468953.000000,153,True,True,False,False,...,981.486945,963316.623333,1.464644,1.058630e+06,2503051.0,80387.0,7.091184e+05,5.028489e+11,0.484967,True
5711,True,85,4197,3302,0.786752,183,True,False,False,False,...,1.164760,1.356667,0.651568,8.404168e+05,1792583.0,117098.0,4.009773e+05,1.607828e+11,0.168065,True
5873,True,0,208,87,0.418269,15,True,False,False,False,...,1.083625,1.174242,1.062322,1.427749e+06,11029128.0,16689.0,3.233217e+06,1.045369e+13,2.697486,True
6078,True,0,1218,389,0.319376,216,True,False,False,False,...,2.478575,6.143333,0.576336,3.436045e+06,31397859.0,67439.0,6.534950e+06,4.270557e+13,3.531584,True
6595,True,0,228,93,0.407895,47,True,False,False,False,...,2.081666,4.333333,3.422604,1.895593e+06,7423845.0,10.0,2.083936e+06,4.342790e+12,1.426538,True
6629,True,128,661,263,0.397882,2,True,False,False,False,...,6.000000,36.000000,0.000000,1.468590e+06,1729097.0,1208084.0,3.684118e+05,1.357273e+11,0.000000,True
6795,True,0,661,417,0.630862,292,True,False,False,False,...,0.637704,0.406667,1.523849,1.345008e+04,111791.0,21.0,2.905158e+04,8.439945e+08,2.475906,True
6887,True,70,831,1121,1.348977,295,True,False,False,False,...,1.508863,2.276667,0.907251,8.239032e+05,3003410.0,162631.0,7.386990e+05,5.456763e+11,1.402957,True
7161,True,57,40,631653,15791.325000,3466,True,False,False,False,...,280.843652,78873.156667,3.628704,7.392458e+03,47193.0,1476.0,9.727521e+03,9.462466e+07,3.239454,True
7901,True,106,5971,1584,0.265282,17,True,False,False,False,...,3.124137,9.760234,1.576205,3.040886e+05,2322332.0,24.0,5.778855e+05,3.339517e+11,2.621431,False
8214,True,142,887,307,0.346110,12,True,False,False,False,...,0.900337,0.810606,2.209942,2.276032e+06,7412448.0,3349.0,3.183989e+06,1.013779e+13,0.972495,False
8361,True,0,123,42,0.341463,9,True,False,False,False,...,0.646670,0.418182,2.077008,3.494561e+05,1489119.0,10.0,5.112816e+05,2.614089e+11,1.288320,False
8454,True,38,1715,442,0.257726,29,True,False,False,False,...,1.695091,2.873333,1.792314,2.100135e+05,1984795.0,525.0,4.274775e+05,1.827370e+11,3.234023,False
8643,True,0,648,224,0.345679,17,True,False,False,False,...,2.373258,5.632353,2.764074,1.801214e+06,3889855.0,63279.0,1.345926e+06,1.811516e+12,0.220887,False
9255,True,3,323,278,0.860681,1,True,False,False,False,...,0.000000,0.000000,0.000000,0.000000e+00,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,False
9849,False,132,1789,599,0.334824,5,True,False,False,False,...,3.214550,10.333333,0.630904,3.576515e+06,5015522.0,2137508.0,2.035063e+06,4.141482e+12,0.000000,False
10322,True,0,193,128,0.663212,134,True,False,False,False,...,0.276887,0.076667,3.096281,4.061081e+05,2064752.0,48.0,5.041802e+05,2.541977e+11,1.737748,False
10739,True,2,870,1923,2.210345,1,True,False,False,False,...,0.000000,0.000000,0.000000,7.819297e+05,4349123.0,21.0,1.752908e+06,3.072687e+12,1.765166,False
10920,True,73,277,2183,7.880866,3,True,False,False,False,...,19.986662,399.466667,0.922938,7.522777e+06,33036219.0,297.0,1.431520e+07,2.049250e+14,1.472863,False
11207,True,122,7446,3301,0.443325,66,True,False,False,False,...,0.600000,0.360000,4.694855,3.493317e+04,144938.0,12.0,4.742033e+04,2.248688e+09,1.120346,False
11260,True,78,1160,333,0.287069,0,True,False,False,False,...,3.535534,12.500000,0.000000,2.253390e+05,225339.0,225339.0,0.000000e+00,0.000000e+00,0.000000,False
11627,True,78,5887,3428,0.582300,3,True,False,False,False,...,3.535534,12.500000,0.000000,3.881496e+06,3881496.0,3881496.0,0.000000e+00,0.000000e+00,0.000000,False
12033,True,66,5207,1195,0.229499,8,True,False,False,False,...,5.147815,26.500000,1.557522,1.324312e+06,2342134.0,99.0,8.691984e+05,7.555058e+11,-0.310981,False
12080,True,0,1515,341,0.225083,6,True,False,False,False,...,1.601282,2.564103,0.777000,1.147215e+06,9605981.0,21.0,2.719059e+06,7.393280e+12,2.815642,False
12107,True,100,42,357,8.500000,11,True,False,False,False,...,2.695896,7.267857,1.637576,7.260506e+05,2166475.0,187456.0,6.833577e+05,4.669778e+11,1.499600,False
12742,True,144,3901,2727,0.699052,997,True,False,False,False,...,0.200000,0.040000,4.694855,3.932488e+04,363787.0,84.0,9.889766e+04,9.780747e+09,2.782947,False
12774,True,60,5847,3579,0.612109,24,True,False,False,False,...,4.144142,17.173913,1.684412,1.158483e+06,5170503.0,88226.0,1.407947e+06,1.982315e+12,1.799975,False
15078,True,150,3916,1607,0.410368,859,True,False,False,False,...,0.000000,0.000000,0.000000,2.792333e+03,47269.0,32.0,9.684331e+03,9.378627e+07,4.291027,False

In [62]:
df.loc[(df['is_private'] ==False)&(df['min_likes'].isnull())&(df['media_count']!=0)]

,profile_pic,biography,follows_count,followed_by_count,ff_ratio,media_count,is_private,is_verified,is_business_account,is_joined_recently,...,std_comments,var_comments,skw_comments,mean_time_between_posts,max_time_between_posts,min_time_between_posts,std_time_between_posts,var_time_between_posts,skw_time_between_posts,real_account
343,True,54,687,2735,3.981077,269,False,False,True,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
853,True,30,472,1411,2.989407,640,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2623,True,44,1347,1237,0.918337,224,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
5277,True,0,13,270,20.769231,16,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
5638,True,9,286,202,0.706294,10,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12995,True,145,6484,1213,0.187076,29,False,False,True,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
13142,True,12,924,151,0.163420,21,False,False,True,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
13770,True,97,6636,1973,0.297318,16811,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
14783,False,0,4474,911,0.203621,1,False,False,True,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
14994,True,0,1591,22,0.013828,15,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

In [63]:
#Fixing the entries with private users (for scraping errors)
df=fix_private_entries(df)

In [64]:
# Fix the dataset with incorrect entries
df.loc[(df['is_private'] ==True)&(df['min_likes'].notnull())]

Empty DataFrame
Columns: [profile_pic, biography, follows_count, followed_by_count, ff_ratio, media_count, is_private, is_verified, is_business_account, is_joined_recently, highlight_reel_count, average_likes, max_likes, min_likes, std_likes, var_likes, skw_likes, average_comments, max_comments, min_comments, std_comments, var_comments, skw_comments, mean_time_between_posts, max_time_between_posts, min_time_between_posts, std_time_between_posts, var_time_between_posts, skw_time_between_posts, real_account]
Index: []

[0 rows x 30 columns]

In [65]:
df.loc[(df['is_private'] ==False)&(df['min_likes'].isnull())&(df['media_count']!=0)]

Empty DataFrame
Columns: [profile_pic, biography, follows_count, followed_by_count, ff_ratio, media_count, is_private, is_verified, is_business_account, is_joined_recently, highlight_reel_count, average_likes, max_likes, min_likes, std_likes, var_likes, skw_likes, average_comments, max_comments, min_comments, std_comments, var_comments, skw_comments, mean_time_between_posts, max_time_between_posts, min_time_between_posts, std_time_between_posts, var_time_between_posts, skw_time_between_posts, real_account]
Index: []

[0 rows x 30 columns]

In [66]:
features_columns=list(df.columns[:30])
# targets_column=list(df.columns[30:31])
print(features_columns)

['profile_pic', 'biography', 'follows_count', 'followed_by_count', 'ff_ratio', 'media_count', 'is_private', 'is_verified', 'is_business_account', 'is_joined_recently', 'highlight_reel_count', 'average_likes', 'max_likes', 'min_likes', 'std_likes', 'var_likes', 'skw_likes', 'average_comments', 'max_comments', 'min_comments', 'std_comments', 'var_comments', 'skw_comments', 'mean_time_between_posts', 'max_time_between_posts', 'min_time_between_posts', 'std_time_between_posts', 'var_time_between_posts', 'skw_time_between_posts', 'real_account']

In [67]:
df.shape

(15308, 30)

In [68]:
targets = df['real_account'].values
df=df.loc[:,'profile_pic':'skw_time_between_posts']

In [69]:
targets

array([ True,  True,  True, ..., False, False, False])