In [5]:
import pandas as pd
#Carico il dataset 
dataset=pd.read_csv("data_fake.csv")

In [6]:
print(dataset)

      profile_pic  biography  follows_count  followed_by_count  ff_ratio  \
0            True       True           2321                747  0.321705
1            True       True           4247                611  0.143832
2            True       True            781                338  0.432225
3            True       True           1764               1613  0.913881
4            True      False             68                 65  0.942029
...           ...        ...            ...                ...       ...
7837         True       True           2323                 72  0.030981
7838         True       True           2311               2934  1.269031
7839         True       True           7498               2340  0.312042
7840         True      False           6321                327  0.051724
7841         True       True           6531                 61  0.009339

      media_count  is_private  is_verified  is_business_account  \
0              10        True        False                False
1              99       False        False                 True
2             128        True        False                False
3              64       False        False                False
4               1       False        False                False
...           ...         ...          ...                  ...
7837           20       False        False                False
7838           55       False        False                False
7839           39       False        False                 True
7840           15       False        False                False
7841            7       False        False                False

      is_joined_recently  ...  std_comments  var_comments  skw_comments  \
0                  False  ...           NaN           NaN           NaN
1                  False  ...           NaN           NaN           NaN
2                  False  ...           NaN           NaN           NaN
3                  False  ...           NaN           NaN           NaN
4                  False  ...           NaN           NaN           NaN
...                  ...  ...           ...           ...           ...
7837               False  ...      6.340347     40.200000      1.582760
7838               False  ...      0.472582      0.223333      2.951336
7839               False  ...      3.329164     11.083333      0.677680
7840               False  ...      2.313521      5.352381      2.028695
7841               False  ...      0.000000      0.000000      0.000000

      mean_time_between_posts  max_time_between_posts  min_time_between_posts  \
0                         NaN                     NaN                     NaN
1                         NaN                     NaN                     NaN
2                         NaN                     NaN                     NaN
3                         NaN                     NaN                     NaN
4                         NaN                     NaN                     NaN
...                       ...                     ...                     ...
7837             2.975948e+05               2685349.0                    23.0
7838             6.898008e+05               6434047.0                   138.0
7839             9.702668e+05               3269496.0                   280.0
7840             3.078766e+06              16860832.0                    10.0
7841             8.326883e+05               1910995.0                522383.0

      std_time_between_posts  var_time_between_posts  skw_time_between_posts  \
0                        NaN                     NaN                     NaN
1                        NaN                     NaN                     NaN
2                        NaN                     NaN                     NaN
3                        NaN                     NaN                     NaN
4                        NaN                     NaN                     NaN
...                      ...                     ...                     ...
7837            7.634178e+05            5.828067e+11                2.578928
7838            1.780056e+06            3.168601e+12                2.400901
7839            7.913546e+05            6.262421e+11                1.132687
7840            5.588747e+06            3.123409e+13                1.579750
7841            5.305299e+05            2.814620e+11                1.753490

      real_account
0            False
1            False
2            False
3            False
4            False
...            ...
7837         False
7838         False
7839         False
7840         False
7841         False

[7842 rows x 31 columns]

In [7]:
dataset.head()

,profile_pic,biography,follows_count,followed_by_count,ff_ratio,media_count,is_private,is_verified,is_business_account,is_joined_recently,...,std_comments,var_comments,skw_comments,mean_time_between_posts,max_time_between_posts,min_time_between_posts,std_time_between_posts,var_time_between_posts,skw_time_between_posts,real_account
0,True,True,2321,747,0.321705,10,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1,True,True,4247,611,0.143832,99,False,False,True,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
2,True,True,781,338,0.432225,128,True,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
3,True,True,1764,1613,0.913881,64,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
4,True,False,68,65,0.942029,1,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

In [8]:
dataset.describe()

,follows_count,followed_by_count,ff_ratio,media_count,highlight_reel_count,average_likes,max_likes,min_likes,std_likes,var_likes,...,min_comments,std_comments,var_comments,skw_comments,mean_time_between_posts,max_time_between_posts,min_time_between_posts,std_time_between_posts,var_time_between_posts,skw_time_between_posts
count,7842.000000,7842.000000,7842.000000,7842.000000,7842.000000,5531.000000,5531.000000,5531.000000,5002.000000,5.002000e+03,...,5531.000000,5002.000000,5.002000e+03,5531.000000,5.002000e+03,5.002000e+03,5.002000e+03,4.689000e+03,4.689000e+03,5002.000000
mean,3011.887656,878.089135,0.643426,131.099847,1.784494,42.802532,92.506780,20.891340,22.383928,5.802373e+03,...,0.392515,3.655663,9.077486e+02,1.407236,1.448237e+06,6.416945e+06,3.653530e+05,2.026147e+06,2.566560e+13,1.676456
std,2643.689645,3544.808749,3.223561,1046.948988,7.532981,119.825723,282.938346,62.876551,72.817528,1.011512e+05,...,3.102436,29.909256,3.325781e+04,1.332064,4.006303e+06,1.503803e+07,3.326005e+06,4.643805e+06,1.770575e+14,1.259847
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,...,0.000000,0.000000,0.000000e+00,-4.694855,1.000000e+00,1.000000e+00,0.000000e+00,4.472136e-01,2.000000e-01,-3.023541
25%,470.250000,61.000000,0.018172,3.000000,0.000000,5.420168,11.000000,2.000000,2.775944,7.705874e+00,...,0.000000,0.377964,1.428571e-01,0.000000,1.080453e+05,5.223520e+05,2.000000e+01,1.400075e+05,1.960209e+10,0.706844
50%,2163.500000,161.500000,0.261928,11.000000,0.000000,15.560000,28.000000,7.000000,6.363961,4.050000e+01,...,0.000000,0.758287,5.750000e-01,1.278019,4.839288e+05,1.880234e+06,1.145000e+02,5.822735e+05,3.390424e+11,1.606342
75%,5874.000000,691.750000,0.623896,54.000000,1.000000,39.792857,77.000000,19.000000,15.768442,2.486439e+02,...,0.000000,1.847939,3.414881e+00,2.267787,1.280637e+06,6.310126e+06,1.434850e+04,1.891050e+06,3.576070e+12,2.465836
max,7551.000000,162061.000000,210.375000,76286.000000,304.000000,5307.000000,10226.000000,2814.000000,2371.476316,5.623900e+06,...,152.000000,1487.967861,2.214048e+06,4.694855,1.647958e+08,2.329249e+08,1.647958e+08,7.587061e+07,5.756350e+15,4.587317