# Naive Bayes with NaN Handling

In [1]:
import pandas as pd
import numpy as np

In [43]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [3]:
df_real = pd.read_csv('../data/balanced_real_data.csv')
df_fake = pd.read_csv('../data/balanced_fake_data.csv')

In [4]:
df_real.head(10)

,username,profile_pic,biography,follows_count,followed_by_count,ff_ratio,media_count,is_private,is_verified,is_business_account,...,std_comments,var_comments,skw_comments,mean_time_between_posts,max_time_between_posts,min_time_between_posts,std_time_between_posts,var_time_between_posts,skw_time_between_posts,real_account
0,irinashayk,True,11,597,13156189,22037.167504,1592,False,True,False,...,878.448591,771671.926667,2.252054,2.077083e+05,611811.0,31545.0,1.719894e+05,2.958036e+10,1.075537,True
1,dementieva_a______,True,0,423,192,0.453901,50,True,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,lorenz.fini,True,0,426,151,0.354460,37,False,False,False,...,2.827248,7.993333,4.049417,2.232875e+06,7637239.0,92.0,2.328249e+06,5.420744e+12,0.828757,True
3,jessicagiulia,True,128,450,694,1.542222,1144,False,False,False,...,1.683251,2.833333,0.963009,1.260785e+05,343781.0,83938.0,8.045028e+04,6.472248e+09,1.596275,True
4,il_socio_aci,True,60,1,327728,327728.000000,392,False,False,True,...,123.279128,15197.743333,2.519276,3.287153e+05,2955259.0,64159.0,5.828985e+05,3.397707e+11,4.056672,True
5,thedavecastro,True,0,0,777086,777086.000000,2216,False,True,False,...,181.741685,33030.040000,1.626493,1.520838e+05,490864.0,45009.0,1.307548e+05,1.709682e+10,1.812694,True
6,heisophie,True,73,484,968,2.000000,91,False,False,False,...,1.524248,2.323333,1.172175,3.098724e+06,31772003.0,81315.0,6.519701e+06,4.250650e+13,3.813986,True
7,lauramarino9026,True,0,408,511,1.252451,27,False,False,False,...,2.758623,7.610000,2.255028,5.760397e+06,83993172.0,1174.0,1.683838e+07,2.835309e+14,4.436249,True
8,secretsupper,True,144,527,2215,4.203036,2438,False,False,True,...,5.671567,32.166667,3.407004,4.402258e+04,154793.0,738.0,4.318317e+04,1.864786e+09,0.681888,True
9,carmenmb99,True,24,1032,1054,1.021318,98,True,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True

In [5]:
df_real.describe()

,biography,follows_count,followed_by_count,ff_ratio,media_count,highlight_reel_count,average_likes,max_likes,min_likes,std_likes,...,min_comments,std_comments,var_comments,skw_comments,mean_time_between_posts,max_time_between_posts,min_time_between_posts,std_time_between_posts,var_time_between_posts,skw_time_between_posts
count,7654.000000,7654.000000,7.654000e+03,7.654000e+03,7654.000000,7654.000000,5.740000e+03,5.740000e+03,5.740000e+03,5.740000e+03,...,5.740000e+03,5740.000000,5.740000e+03,5740.000000,5.740000e+03,5.740000e+03,5.740000e+03,5.740000e+03,5.740000e+03,5740.000000
mean,61.598249,905.962765,6.488189e+05,3.561162e+04,710.938202,5.868957,2.708125e+04,6.099514e+04,1.017885e+04,1.277458e+04,...,1.327234e+03,225.784483,7.782477e+06,1.654237,1.258387e+06,6.226126e+06,1.066066e+05,1.606449e+06,1.280795e+13,1.661835
std,51.755602,1096.540031,6.624957e+06,1.594463e+06,1624.065449,20.296784,3.124552e+05,5.079876e+05,2.544298e+05,9.879527e+04,...,9.787443e+04,2780.799407,2.896920e+08,0.993215,2.774603e+06,1.159586e+07,1.843771e+06,3.198288e+06,9.624537e+13,0.972954
min,0.000000,0.000000,2.000000e+00,6.508135e-02,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000,0.000000e+00,-1.283251,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-3.862198
25%,10.000000,340.000000,5.102500e+02,8.737793e-01,78.000000,0.000000,5.900000e+01,1.130000e+02,2.300000e+01,2.064342e+01,...,0.000000e+00,2.020726,4.083333e+00,0.950908,2.091719e+05,6.937215e+05,2.587250e+03,1.737312e+05,3.018260e+10,1.006976
50%,54.000000,611.000000,1.148000e+03,1.626246e+00,238.000000,2.000000,1.418600e+02,2.790000e+02,6.100000e+01,5.146882e+01,...,0.000000e+00,4.182902,1.749667e+01,1.469455,5.716717e+05,2.419481e+06,3.039850e+04,6.049160e+05,3.659234e+11,1.545573
75%,109.000000,1010.750000,1.277350e+04,1.824791e+01,651.750000,7.000000,1.155080e+03,2.808000e+03,3.440000e+02,5.987826e+02,...,2.000000e+00,18.181010,3.305492e+02,2.176807,1.462746e+06,6.926110e+06,8.326575e+04,1.748441e+06,3.057046e+12,2.198731
max,150.000000,7832.000000,3.239658e+08,1.374144e+08,33287.000000,1143.000000,1.872444e+07,1.872444e+07,1.872444e+07,3.013303e+06,...,7.415231e+06,130429.914201,1.701196e+10,4.694855,1.369621e+08,1.749978e+08,1.369621e+08,5.933687e+07,3.520864e+15,4.587317

In [6]:
df_real.fillna(df_real.median(),inplace=True)

In [7]:
df_fake.fillna(df_fake.median(),inplace=True)
df_fake.head()

,username,profile_pic,biography,follows_count,followed_by_count,ff_ratio,media_count,is_private,is_verified,is_business_account,...,std_comments,var_comments,skw_comments,mean_time_between_posts,max_time_between_posts,min_time_between_posts,std_time_between_posts,var_time_between_posts,skw_time_between_posts,real_account
0,_s.a.v.a__v.l.a.d_,True,56,2321,747,0.321844,10,True,False,False,...,0.593617,0.352381,1.228785,345743.041667,1356538.0,60.0,3.530669e+05,1.246562e+11,1.429528,False
1,pp_sport_julduz,True,147,4247,611,0.143866,99,False,False,True,...,0.678233,0.460000,2.068805,80254.208333,1466742.0,10.0,2.973342e+05,8.840762e+10,4.488934,False
2,clark5.7lyfe,True,127,1764,1613,0.914399,64,False,False,False,...,10.224643,104.543333,3.196293,333885.000000,836121.0,27637.0,2.240602e+05,5.020299e+10,0.519589,False
3,nata53149,True,0,68,65,0.955882,1,False,False,False,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000e+00,0.000000e+00,0.000000,False
4,olgashatko.63,True,80,242,134,0.553719,80,False,False,False,...,0.624500,0.390000,4.086591,694503.000000,6477346.0,8.0,1.489132e+06,2.217513e+12,2.800966,False

In [8]:
df=pd.concat([df_real,df_fake],ignore_index=True)

In [9]:
print(df)

                  username  profile_pic  biography  follows_count  \
0               irinashayk         True         11            597
1       dementieva_a______         True          0            423
2              lorenz.fini         True          0            426
3            jessicagiulia         True        128            450
4             il_socio_aci         True         60              1
...                    ...          ...        ...            ...
15303           tanku26_02         True         31           1440
15304      leyes.naturales         True          3           3040
15305           dyakonov05         True          0           6638
15306  jason_steven_kettle         True         66           4501
15307           ramon.educ         True         45            695

       followed_by_count       ff_ratio  media_count  is_private  is_verified  \
0               13156189   22037.167504         1592       False         True
1                    192       0.453901           50        True        False
2                    151       0.354460           37       False        False
3                    694       1.542222         1144       False        False
4                 327728  327728.000000          392       False        False
...                  ...            ...          ...         ...          ...
15303                504       0.350000           12        True        False
15304                 43       0.014145            3       False        False
15305                 86       0.012956            1       False        False
15306              10424       2.315930           63       False        False
15307                 18       0.025899            3       False        False

       is_business_account  ...  std_comments   var_comments  skw_comments  \
0                    False  ...    878.448591  771671.926667      2.252054
1                    False  ...      4.182902      17.496667      1.469455
2                    False  ...      2.827248       7.993333      4.049417
3                    False  ...      1.683251       2.833333      0.963009
4                     True  ...    123.279128   15197.743333      2.519276
...                    ...  ...           ...            ...           ...
15303                False  ...      0.593617       0.352381      1.228785
15304                False  ...      0.000000       0.000000      0.000000
15305                False  ...      0.000000       0.000000      0.000000
15306                False  ...      5.473268      29.956667      0.564568
15307                False  ...      0.577350       0.333333      0.707107

       mean_time_between_posts  max_time_between_posts  \
0                 2.077083e+05                611811.0
1                 5.716717e+05               2419481.0
2                 2.232875e+06               7637239.0
3                 1.260785e+05                343781.0
4                 3.287153e+05               2955259.0
...                        ...                     ...
15303             3.457430e+05               1356538.0
15304             9.456275e+05               1890345.0
15305             0.000000e+00                     0.0
15306             5.045359e+05               3194892.0
15307             6.900000e+01                   106.0

       min_time_between_posts  std_time_between_posts  var_time_between_posts  \
0                     31545.0            1.719894e+05            2.958036e+10
1                     30398.5            6.049160e+05            3.659234e+11
2                        92.0            2.328249e+06            5.420744e+12
3                     83938.0            8.045028e+04            6.472248e+09
4                     64159.0            5.828985e+05            3.397707e+11
...                       ...                     ...                     ...
15303                    60.0            3.530669e+05            1.246562e+11
15304                   910.0            1.336032e+06            1.784982e+12
15305                     0.0            0.000000e+00            0.000000e+00
15306                  4898.0            8.275372e+05            6.848179e+11
15307                    32.0            5.232590e+01            2.738000e+03

       skw_time_between_posts  real_account
0                    1.075537          True
1                    1.545573          True
2                    0.828757          True
3                    1.596275          True
4                    4.056672          True
...                       ...           ...
15303                1.429528         False
15304                0.000000         False
15305                0.000000         False
15306                2.331393         False
15307                0.000000         False

[15308 rows x 31 columns]

In [10]:
# df.drop('Unnamed: 0', axis=1, inplace=True)

In [11]:
features_columns=list(df.columns[:30])
# targets_column=list(df.columns[30:31])
# df.head()
print(features_columns)

['username', 'profile_pic', 'biography', 'follows_count', 'followed_by_count', 'ff_ratio', 'media_count', 'is_private', 'is_verified', 'is_business_account', 'is_joined_recently', 'highlight_reel_count', 'average_likes', 'max_likes', 'min_likes', 'std_likes', 'var_likes', 'skw_likes', 'average_comments', 'max_comments', 'min_comments', 'std_comments', 'var_comments', 'skw_comments', 'mean_time_between_posts', 'max_time_between_posts', 'min_time_between_posts', 'std_time_between_posts', 'var_time_between_posts', 'skw_time_between_posts']

In [12]:
df.shape

(15308, 31)

In [13]:
# cl_f = {'pos': 1, 'neg': 0}
# df['Class'] = df['Class'].map(cl_f)

In [14]:
df.dropna(inplace=True)
df.shape
df=df.loc[:,'profile_pic':]

In [15]:
targets = df['real_account'].values

In [16]:
targets

array([ True,  True,  True, ..., False, False, False])

In [17]:
# df.drop('real_account', axis=1, inplace=True)

In [18]:
df.head()

,profile_pic,biography,follows_count,followed_by_count,ff_ratio,media_count,is_private,is_verified,is_business_account,is_joined_recently,...,std_comments,var_comments,skw_comments,mean_time_between_posts,max_time_between_posts,min_time_between_posts,std_time_between_posts,var_time_between_posts,skw_time_between_posts,real_account
0,True,11,597,13156189,22037.167504,1592,False,True,False,False,...,878.448591,771671.926667,2.252054,2.077083e+05,611811.0,31545.0,1.719894e+05,2.958036e+10,1.075537,True
1,True,0,423,192,0.453901,50,True,False,False,False,...,4.182902,17.496667,1.469455,5.716717e+05,2419481.0,30398.5,6.049160e+05,3.659234e+11,1.545573,True
2,True,0,426,151,0.354460,37,False,False,False,False,...,2.827248,7.993333,4.049417,2.232875e+06,7637239.0,92.0,2.328249e+06,5.420744e+12,0.828757,True
3,True,128,450,694,1.542222,1144,False,False,False,False,...,1.683251,2.833333,0.963009,1.260785e+05,343781.0,83938.0,8.045028e+04,6.472248e+09,1.596275,True
4,True,60,1,327728,327728.000000,392,False,False,True,False,...,123.279128,15197.743333,2.519276,3.287153e+05,2955259.0,64159.0,5.828985e+05,3.397707e+11,4.056672,True

In [19]:
df.shape

(15308, 30)

In [20]:
print(df)

       profile_pic  biography  follows_count  followed_by_count  \
0             True         11            597           13156189
1             True          0            423                192
2             True          0            426                151
3             True        128            450                694
4             True         60              1             327728
...            ...        ...            ...                ...
15303         True         31           1440                504
15304         True          3           3040                 43
15305         True          0           6638                 86
15306         True         66           4501              10424
15307         True         45            695                 18

            ff_ratio  media_count  is_private  is_verified  \
0       22037.167504         1592       False         True
1           0.453901           50        True        False
2           0.354460           37       False        False
3           1.542222         1144       False        False
4      327728.000000          392       False        False
...              ...          ...         ...          ...
15303       0.350000           12        True        False
15304       0.014145            3       False        False
15305       0.012956            1       False        False
15306       2.315930           63       False        False
15307       0.025899            3       False        False

       is_business_account  is_joined_recently  ...  std_comments  \
0                    False               False  ...    878.448591
1                    False               False  ...      4.182902
2                    False               False  ...      2.827248
3                    False               False  ...      1.683251
4                     True               False  ...    123.279128
...                    ...                 ...  ...           ...
15303                False               False  ...      0.593617
15304                False               False  ...      0.000000
15305                False               False  ...      0.000000
15306                False               False  ...      5.473268
15307                False               False  ...      0.577350

        var_comments  skw_comments  mean_time_between_posts  \
0      771671.926667      2.252054             2.077083e+05
1          17.496667      1.469455             5.716717e+05
2           7.993333      4.049417             2.232875e+06
3           2.833333      0.963009             1.260785e+05
4       15197.743333      2.519276             3.287153e+05
...              ...           ...                      ...
15303       0.352381      1.228785             3.457430e+05
15304       0.000000      0.000000             9.456275e+05
15305       0.000000      0.000000             0.000000e+00
15306      29.956667      0.564568             5.045359e+05
15307       0.333333      0.707107             6.900000e+01

       max_time_between_posts  min_time_between_posts  std_time_between_posts  \
0                    611811.0                 31545.0            1.719894e+05
1                   2419481.0                 30398.5            6.049160e+05
2                   7637239.0                    92.0            2.328249e+06
3                    343781.0                 83938.0            8.045028e+04
4                   2955259.0                 64159.0            5.828985e+05
...                       ...                     ...                     ...
15303               1356538.0                    60.0            3.530669e+05
15304               1890345.0                   910.0            1.336032e+06
15305                     0.0                     0.0            0.000000e+00
15306               3194892.0                  4898.0            8.275372e+05
15307                   106.0                    32.0            5.232590e+01

       var_time_between_posts  skw_time_between_posts  real_account
0                2.958036e+10                1.075537          True
1                3.659234e+11                1.545573          True
2                5.420744e+12                0.828757          True
3                6.472248e+09                1.596275          True
4                3.397707e+11                4.056672          True
...                       ...                     ...           ...
15303            1.246562e+11                1.429528         False
15304            1.784982e+12                0.000000         False
15305            0.000000e+00                0.000000         False
15306            6.848179e+11                2.331393         False
15307            2.738000e+03                0.000000         False

[15308 rows x 30 columns]

In [44]:
df_sc = StandardScaler().fit_transform(df)

In [45]:
x_train, x_test, y_train, y_test = train_test_split(df_sc, targets, test_size = 0.99, random_state = 12345)

In [46]:
nb = GaussianNB()

In [47]:
nb.fit(x_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [48]:
nb_pred = nb.predict(x_test)

In [49]:
x_test[147].reshape(1,-1)

array([[0.00000000e+00, 0.00000000e+00, 7.45658836e-02, 1.16061648e-06,
        4.68535746e-09, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 7.56230894e-07,
        1.33515341e-06, 3.20436819e-07, 1.63061513e-06, 2.65890571e-12,
        4.60541265e-01, 5.93373288e-08, 2.69715131e-07, 0.00000000e+00,
        4.55123231e-06, 2.07137155e-11, 6.30865015e-01, 2.09800901e-03,
        5.82392816e-03, 3.64086982e-07, 4.65353950e-03, 2.16554299e-05,
        6.26275715e-01, 0.00000000e+00]])

In [50]:
nb.predict(x_test[14].reshape(1,-1))

array([ True])

In [51]:
from sklearn.metrics import confusion_matrix, classification_report

In [52]:
print(confusion_matrix(y_test, nb_pred))

[[7584    0]
 [   9 7562]]

In [53]:
print(classification_report(y_test, nb_pred))

              precision    recall  f1-score   support

       False       1.00      1.00      1.00      7584
        True       1.00      1.00      1.00      7571

    accuracy                           1.00     15155
   macro avg       1.00      1.00      1.00     15155
weighted avg       1.00      1.00      1.00     15155

In [54]:
print(df[df['is_private']==True])

       profile_pic  biography  follows_count  followed_by_count  ff_ratio  \
1             True          0            423                192  0.453901
9             True         24           1032               1054  1.021318
10            True          0            605                320  0.528926
15            True         21           1007                453  0.449851
18            True         69            728                957  1.314560
...            ...        ...            ...                ...       ...
15276         True         33            547                322  0.588665
15281         True          0            155                139  0.896774
15292         True         14           7077                899  0.127031
15302         True         62            912                945  1.036184
15303         True         31           1440                504  0.350000

       media_count  is_private  is_verified  is_business_account  \
1               50        True        False                False
9               98        True        False                False
10             174        True        False                False
15               8        True        False                False
18              18        True        False                False
...            ...         ...          ...                  ...
15276            8        True        False                False
15281            5        True        False                False
15292           13        True        False                False
15302          513        True        False                False
15303           12        True        False                False

       is_joined_recently  ...  std_comments  var_comments  skw_comments  \
1                   False  ...      4.182902     17.496667      1.469455
9                   False  ...      4.182902     17.496667      1.469455
10                  False  ...      4.182902     17.496667      1.469455
15                   True  ...      4.182902     17.496667      1.469455
18                  False  ...      4.182902     17.496667      1.469455
...                   ...  ...           ...           ...           ...
15276               False  ...      0.593617      0.352381      1.228785
15281               False  ...      0.593617      0.352381      1.228785
15292               False  ...      0.593617      0.352381      1.228785
15302               False  ...      0.593617      0.352381      1.228785
15303               False  ...      0.593617      0.352381      1.228785

       mean_time_between_posts  max_time_between_posts  \
1                571671.708333               2419481.0
9                571671.708333               2419481.0
10               571671.708333               2419481.0
15               571671.708333               2419481.0
18               571671.708333               2419481.0
...                        ...                     ...
15276            345743.041667               1356538.0
15281            345743.041667               1356538.0
15292            345743.041667               1356538.0
15302            345743.041667               1356538.0
15303            345743.041667               1356538.0

       min_time_between_posts  std_time_between_posts  var_time_between_posts  \
1                     30398.5           604915.979694            3.659234e+11
9                     30398.5           604915.979694            3.659234e+11
10                    30398.5           604915.979694            3.659234e+11
15                    30398.5           604915.979694            3.659234e+11
18                    30398.5           604915.979694            3.659234e+11
...                       ...                     ...                     ...
15276                    60.0           353066.892697            1.246562e+11
15281                    60.0           353066.892697            1.246562e+11
15292                    60.0           353066.892697            1.246562e+11
15302                    60.0           353066.892697            1.246562e+11
15303                    60.0           353066.892697            1.246562e+11

       skw_time_between_posts  real_account
1                    1.545573          True
9                    1.545573          True
10                   1.545573          True
15                   1.545573          True
18                   1.545573          True
...                       ...           ...
15276                1.429528         False
15281                1.429528         False
15292                1.429528         False
15302                1.429528         False
15303                1.429528         False

[2945 rows x 30 columns]